# Generated by Django 4.2.6 on 2023-10-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("detail", models.CharField(max_length=125, verbose_name="Details")),
                (
                    "create_time",
                    models.CharField(
                        db_column="create_time",
                        max_length=19,
                        verbose_name="Create Time",
                    ),
                ),
            ],
            options={
                "db_table": "notices",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.CharField(
                        db_column="create_time",
                        max_length=19,
                        verbose_name="Create Time",
                    ),
                ),
                ("confirm", models.IntegerField(verbose_name="Confirmed Cases")),
                ("heal", models.IntegerField(verbose_name="Healed Cases")),
                ("dead", models.IntegerField(verbose_name="Dead Cases")),
                (
                    "nowConfirm",
                    models.IntegerField(
                        db_column="now_confirm",
                        verbose_name="Currently Confirmed Cases",
                    ),
                ),
            ],
            options={
                "db_table": "statistics",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "userName",
                    models.CharField(
                        db_column="User Name", max_length=32, verbose_name="Username"
                    ),
                ),
                ("password", models.CharField(max_length=32, verbose_name="Password")),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("gender", models.CharField(max_length=2, verbose_name="Gender")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("phone", models.CharField(max_length=11, verbose_name="Phone")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("type", models.IntegerField(verbose_name="Type")),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="VaccinateLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("card", models.CharField(max_length=32, verbose_name="Card ID")),
                ("phone", models.CharField(max_length=11, verbose_name="Phone")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("details", models.CharField(max_length=125, verbose_name="Details")),
                (
                    "vaccinateNo",
                    models.CharField(
                        db_column="vaccinate_no",
                        max_length=32,
                        verbose_name="Number of Vaccination",
                    ),
                ),
                (
                    "vaccinateTime",
                    models.CharField(
                        db_column="vaccinate_time",
                        max_length=19,
                        verbose_name="Vaccination Time",
                    ),
                ),
                (
                    "use",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "vaccinate_log",
            },
        ),
        migrations.CreateModel(
            name="Checklog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.CharField(
                        db_column="create_time",
                        max_length=19,
                        verbose_name="Create Time",
                    ),
                ),
                ("detail", models.CharField(max_length=125, verbose_name="Details")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "check_log",
            },
        ),
        migrations.CreateModel(
            name="AbnormityLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.CharField(
                        db_column="create_time",
                        max_length=19,
                        verbose_name="Create Time",
                    ),
                ),
                ("details", models.CharField(max_length=125, verbose_name="Details")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "abnormity_log",
            },
        ),
    ]
